### ISSUE TITLE
Add a carousel to the homepage.

### ISSUE THREAD

**Issue by Kyle-L** [LMLI-Cohort-9/Envision-2040#19]
Add a carousel to the homepage that rotates through the various categories.

**Comment by KabirArora76** [comment]
https://react-bootstrap.github.io/components/carousel/
https://www.w3schools.com/w3css/w3css_slideshow.asp

**Comment by Kyle-L** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Test](https://trello.com/c/jtY9qwGL/1-test)
